In [11]:
import pandas as pd

df = pd.read_csv('IMDB-Movie-Data.csv')

In [12]:
df

,Rank,Title,Genre,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76
1,2,Prometheus,"Adventure,Mystery,Sci-Fi",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65
2,3,Split,"Horror,Thriller",M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62
3,4,Sing,"Animation,Comedy,Family",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59
4,5,Suicide Squad,"Action,Adventure,Fantasy",David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,0.00,45
996,997,Hostel: Part II,Horror,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50
998,999,Search Party,"Adventure,Comedy",Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,0.00,22
999,1000,Nine Lives,"Comedy,Family,Fantasy",Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11

In [13]:
df['Genre'] = df['Genre'].str.replace(',', '|')
df['Actors'] = df['Actors'].str.replace(',', '|')
df['Director'] = df['Director'].str.replace(',', '|')
df['Genre']

0       Action|Adventure|Sci-Fi
1      Adventure|Mystery|Sci-Fi
2               Horror|Thriller
3       Animation|Comedy|Family
4      Action|Adventure|Fantasy
                 ...
995         Crime|Drama|Mystery
996                      Horror
997         Drama|Music|Romance
998            Adventure|Comedy
999       Comedy|Family|Fantasy
Name: Genre, Length: 1000, dtype: object

In [14]:
df

,Rank,Title,Genre,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,Action|Adventure|Sci-Fi,James Gunn,Chris Pratt| Vin Diesel| Bradley Cooper| Zoe S...,2014,121,8.1,757074,333.13,76
1,2,Prometheus,Adventure|Mystery|Sci-Fi,Ridley Scott,Noomi Rapace| Logan Marshall-Green| Michael Fa...,2012,124,7.0,485820,126.46,65
2,3,Split,Horror|Thriller,M. Night Shyamalan,James McAvoy| Anya Taylor-Joy| Haley Lu Richar...,2016,117,7.3,157606,138.12,62
3,4,Sing,Animation|Comedy|Family,Christophe Lourdelet,Matthew McConaughey|Reese Witherspoon| Seth Ma...,2016,108,7.2,60545,270.32,59
4,5,Suicide Squad,Action|Adventure|Fantasy,David Ayer,Will Smith| Jared Leto| Margot Robbie| Viola D...,2016,123,6.2,393727,325.02,40
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,Crime|Drama|Mystery,Billy Ray,Chiwetel Ejiofor| Nicole Kidman| Julia Roberts...,2015,111,6.2,27585,0.00,45
996,997,Hostel: Part II,Horror,Eli Roth,Lauren German| Heather Matarazzo| Bijou Philli...,2007,94,5.5,73152,17.54,46
997,998,Step Up 2: The Streets,Drama|Music|Romance,Jon M. Chu,Robert Hoffman| Briana Evigan| Cassie Ventura|...,2008,98,6.2,70699,58.01,50
998,999,Search Party,Adventure|Comedy,Scot Armstrong,Adam Pally| T.J. Miller| Thomas Middleditch|Sh...,2014,93,5.6,4881,0.00,22
999,1000,Nine Lives,Comedy|Family|Fantasy,Barry Sonnenfeld,Kevin Spacey| Jennifer Garner| Robbie Amell|Ch...,2016,87,5.3,12435,19.64,11

In [15]:
df.to_csv('IMDB-Movie-Data.csv')